name: 'Send Font News Bot'
on:
  push:
    branches:
      - main
  schedule:
    # 定时任务，在每天的9点
    - cron: "0 1 * * *"

env:
  FONT_WECOM_WEBHOOK_KEY: ${{ secrets.FONT_WECOM_WEBHOOK_KEY }}

jobs:
  run-sendFontNews:
    runs-on: ubuntu-latest
    steps:
      # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '14'
          
      - name: Install Dependency       
        run: |
          npm install       
          node ./getNewsSendToWecom.js  # 要运行的js脚本，放在根目录下

# name: 'Send Font News Bot'
 
# on:
#   push:
#   schedule:
#   # 定时任务，在每天的9点推送天气信息到邮箱
#     - cron: '0 1 * * *'

# env:
#   FONT_WECOM_WEBHOOK_KEY: ${{ secrets.FONT_WECOM_WEBHOOK_KEY }}

# jobs:
#   bot:
#     runs-on: ubuntu-latest
#     steps:
#     # 首先copy git仓库到虚拟机上
#       - name: 'Checkout codes'
#         uses: actions/checkout@v1
#       - name: Setup Node.js
#         uses: actions/setup-node@v2  #安装node.js
#         with:
#           node-version: '14'
          
#       - name: Install Dependency       
#         run: |
#           npm install       
#           node ./font-news.js  # 要运行的js脚本，放在根目录下
